# Generated by Django 4.1.dev20210928112014 on 2021-09-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='associates',
            new_name='associate',
        ),
    ]
