# Generated by Django 4.1.dev20210928112014 on 2021-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0004_alter_associate_contactemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='contactemail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
