# Generated by Django 4.1.dev20210928112014 on 2021-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0005_alter_associate_contactemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='enddate',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='givenname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='hiredate',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='managerid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
