# Generated by Django 4.1.dev20210928112014 on 2021-10-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0006_alter_associate_enddate_alter_associate_givenname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
